### ISSUE TITLE
Empty translation not resolved correctly

### ISSUE THREAD

**Issue by AndreasVolkmann** [jhipster/react-jhipster#45] opened 2020-03-02 20:27 UTC
Just tried out the Japanese translation and got the following:
![image](https://user-images.githubusercontent.com/9032394/75714563-3d50a300-5ccc-11ea-82ce-cda4e58880fe.png)

The json file looks like this:
```json
"authenticated": {
  "prefix": "",
  "link": "認証",
  "suffix": "を試したければ, デフォルトアカウント:<br/>- 管理者 (ユーザー名=\"admin\", パスワード=\"admin\") <br/>- ユーザー (login=\"user\", password=\"user\")."
}
```

In the translation, the prefix is an empty string, but it is shown as missing.

**Comment by SoniaLahi** [comment] 2020-03-10 09:51
Please follow the guideline when submitting an issue : add the files requested, more details if needed...

About the issue, this behavior is specific to react apps. I could not reproduce it on an angular or vue.js app.

**Comment by SoniaLahi** [comment] 2020-03-10 15:37
I am working on it

**Comment by deepu105** [comment] 2020-03-10 21:00
Thanks @SoniaLahi

**Comment by SoniaLahi** [comment] 2020-04-07 14:47
Btw, here is the current behavior depending on the frameworks : 

|  | vue | angular | react |
|---|---|---|---| 
| ""  |  nothing is displayed | nothing is displayed  | translation-not-found | 
| 0  |  key is displayed | 0  | translation-not-found | 
| "0"  | 0 | 0 | 0 | 
| false | key is displayed | false | translation-not-found | 
| "false" | false | false | false | 

I am fixing it for "", 0 and false

**Comment by SoniaLahi** [comment] 2020-10-10 00:07
Hi @deepu105, the pull request has been merged. This issue should be closed, shouldn't it?

**Closed** 2020-10-10 09:01 UTC

**Comment by deepu105** [comment] 2020-10-10 11:08
Thank you Sonia
